export const ENTERPRISE_ROLES = {
  ADMIN: 'ADMIN',
  EVENT_STAFF: 'EVENT_STAFF',
  FINANCE: 'FINANCE',
  EXPERT: 'EXPERT',
} as const

export const ENTERPRISE_NAV_ROLES: Record<string, string[]> = {
  '/enterprise/dashboard': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF, ENTERPRISE_ROLES.FINANCE, ENTERPRISE_ROLES.EXPERT],
  '/enterprise/members': [ENTERPRISE_ROLES.ADMIN],
  '/enterprise/attendees': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF],
  '/enterprise/events': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF],
  '/enterprise/papers': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF],
  '/enterprise/reviews': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EXPERT],
  '/enterprise/hotels': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF],
  '/enterprise/bookings': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF, ENTERPRISE_ROLES.FINANCE],
  '/enterprise/email-templates': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.EVENT_STAFF],
  '/enterprise/finance/orders': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.FINANCE],
  '/enterprise/finance/invoices': [ENTERPRISE_ROLES.ADMIN, ENTERPRISE_ROLES.FINANCE],
}
